### ISSUE TITLE
Template "entity/view/partials/actions/toggle-controls" is not defined () in "entity/page/pending" at line 7.

### ISSUE THREAD

**Issue by arekkas** [serlo-org/athene2#10]
@inyono could you fix this?

https://de.serlo.org/entity/view/35503

```
Template "entity/view/partials/actions/toggle-controls" is not defined () in "entity/page/pending" at line 7.
```

```
#0 /home/www/athene2.serlo.org/athene2/src/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('entity/view/par...')
#1 /home/www/athene2.serlo.org/athene2/src/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('entity/view/par...', NULL)
#2 /home/www/athene2.serlo.org/athene2/src/data/twig/a9/6a/39f754b00a16481ac7933caf347a6ad302f33306c731d688554fcc48e209.php(31): Twig_Environment->loadTemplate('entity/view/par...')
#3 /home/www/athene2.serlo.org/athene2/src/vendor/twig/twig/lib/Twig/Template.php(289): __TwigTemplate_a96a39f754b00a16481ac7933caf347a6ad302f33306c731d688554fcc48e209->doDisplay(Array, Array)
#4 /home/www/athene2.serlo.org/athene2/src/vendor/twig/twig/lib/Twig/Template.php(263): Twig_Template->displayWithErrorHandling(Array, Array)
#5 /home/www/athene2.serlo.org/athene2/src/vendor/twig/twig/lib/Twig/Template.php(274): Twig_Template->display(Array)
#6 /home/www/athene2.serlo.org/athene2/src/vendor/zf-commons/zfc-twig/src/ZfcTwig/View/TwigRenderer.php(229): Twig_Template->render(Array)
#7 /home/www/athene2.serlo.org/athene2/src/data/classes.php.cache(85): ZfcTwig\View\TwigRenderer->render(Object(Zend\View\Model\ViewModel))
#8 /home/www/athene2.serlo.org/athene2/src/data/classes.php.cache(85): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#9 /home/www/athene2.serlo.org/athene2/src/data/classes.php.cache(85): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#10 /home/www/athene2.serlo.org/athene2/src/vendor/zendframework/zendframework/library/Zend/Mvc/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#11 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#12 /home/www/athene2.serlo.org/athene2/src/data/classes.php.cache(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /home/www/athene2.serlo.org/athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#14 /home/www/athene2.serlo.org/athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#15 /home/www/athene2.serlo.org/athene2/src/data/classes.php.cache(2): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#16 /home/www/athene2.serlo.org/athene2/src/public/index.php(25): Zend\Mvc\Application->run()
#17 {main}
```

**Comment by arekkas** [comment]
or @philer @daFischer

**Comment by philer** [comment]
Das ging aber fix. :D
