### ISSUE TITLE
Video einbinden - schwerwiegender Fehler

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#236]
https://de.serlo.org/entity/repository/add-revision/48099

Wollte hier ein Video hinzufügen: https://de.serlo.org/mathe/funktionen/kurvendiskussion/uebersicht-kurvendiskussion

**Comment by arekkas** [comment]
Bei Fehlern bekommt man immer einen Code mit, dieser Code beinhaltet verschlüsselte Informationen zum Problem. Mit Hilfe des Codes kann ich also genau sagen, was der Fehler ist. Falls das Problem nochmals auftreten sollte, kopiere bitte diesen Code hier mit rein, damit ich die Ursache finden kann.

**Comment by SimonKoehl** [comment]
ich hab danach gesucht, weil ich weiß dass der code unter dem Video steht aber konnte nicht runterscrollen. Der Bildschirm hat das Video etwa in der hälfte abgeschnitten und weiter runter ging es irgendwie nicht

**Comment by arekkas** [comment]
Ok, ist reproduzierbar. Ursache:

```
#0 /athene2/src/module/Normalizer/src/Normalizer/Entity/Metadata.php(171): exception_error_handler(4096, 'Argument 1 pass...', '/home/www/athen...', 171, Array)
#1 /athene2/src/data/classes.php.cache(2): Normalizer\Entity\Metadata->setLastModified(NULL)
#2 /athene2/src/data/classes.php.cache(2): Zend\Stdlib\AbstractOptions->__set('lastModified', NULL)
#3 /athene2/src/data/classes.php.cache(2): Zend\Stdlib\AbstractOptions->setFromArray(Array)
#4 /athene2/src/module/Normalizer/src/Normalizer/Entity/Metadata.php(61): Zend\Stdlib\AbstractOptions->__construct(Array)
#5 /athene2/src/module/Normalizer/src/Normalizer/Entity/Normalized.php(73): Normalizer\Entity\Metadata->__construct(Array)
#6 /athene2/src/module/Search/src/Search/Provider/EntityProvider.php(111): Normalizer\Entity\Normalized->getMetadata()
#7 /athene2/src/module/Search/src/Search/SearchService.php(58): Search\Provider\EntityProvider->toDocument(Object(Entity\Entity\Entity))
#8 /athene2/src/module/Search/src/Search/Listener/RepositoryManagerListener.php(39): Search\SearchService->add(Object(Entity\Entity\Entity))
#9 [internal function]: Search\Listener\RepositoryManagerListener->onCheckout(Object(Zend\EventManager\Event))
#10 /athene2/src/data/classes.php.cache(2): call_user_func(Array, Object(Zend\EventManager\Event))
#11 /athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->triggerListeners('checkout', Object(Zend\EventManager\Event), NULL)
#12 /athene2/src/module/Versioning/src/Versioning/RepositoryManager.php(77): Zend\EventManager\EventManager->trigger('checkout', Object(Versioning\RepositoryManager), Array)
#13 /athene2/src/module/Entity/src/Entity/Controller/RepositoryController.php(52): Versioning\RepositoryManager->checkoutRevision(Object(Entity\Entity\Entity), Object(Entity\Entity\Revision))
#14 /athene2/src/data/classes.php.cache(85): Entity\Controller\RepositoryController->addRevisionAction()
#15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /athene2/src/data/classes.php.cache(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /athene2/src/data/classes.php.cache(85): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /athene2/src/data/classes.php.cache(2): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#21 /athene2/src/data/classes.php.cache(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#22 /athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#23 /athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /athene2/src/public/index.php(25): Zend\Mvc\Application->run()
#25 {main}
```

**Comment by arekkas** [comment]
(da hat aber wohl schon länger niemand mehr ein Video erstellt)
