### ISSUE TITLE
macOS: postinstall fails

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#514]
when running `(cd src/assets; npm install)`:

```
> athene2-assets@0.0.0 postinstall /Users/inyono/Projects/athene2/src/assets
> npm-run-all bower build

/Users/inyono/Projects/athene2/src/assets/node_modules/npm-run-all/bin/common/bootstrap.js:14
    const argv = process.argv.slice(2)
    ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/inyono/Projects/athene2/src/assets/node_modules/npm-run-all/bin/npm-run-all/index.js:13:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/inyono/.nvm/versions/node/v0.12.18/bin/node" "/Users/inyono/.nvm/versions/node/v0.12.18/bin/npm" "install"
npm ERR! node v0.12.18
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! athene2-assets@0.0.0 postinstall: `npm-run-all bower build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the athene2-assets@0.0.0 postinstall script 'npm-run-all bower build'.
npm ERR! This is most likely a problem with the athene2-assets package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all bower build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs athene2-assets
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls athene2-assets
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/inyono/Projects/athene2/src/assets/npm-debug.log
```

Any ideas @arekkas @Knorrke? Otherwise, I will debug this ^^ (Seems like `npm-run-all` expects Node v4)

(and yeah, `0.12.15` also fails)

**Comment by inyono** [comment]
By the way, wasn't `0.10.*` our legacy version? xD

**Comment by Knorrke** [comment]
sorry for the late reply, but can you for now run
```
npm run bower
npm run build
```
after `npm install`? Or is there a problem too?

**Comment by inyono** [comment]
I fixed it locally by downgrading some modules. Since it currently affects only me, I didn't create a PR yet.

**Comment by arekkas** [comment]
i guess this will be resolved with the new build system?

**Comment by inyono** [comment]
Yes
