### ISSUE TITLE
docker: en.serlo.localhost broken

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#617]
```
Fatal error: Uncaught Exception: Either gettext is not enabled or locale en_GB.UTF-8 is not installed on this system in /var/www/html/src/module/Instance/Module.php:78 Stack trace: #0 [internal function]: Instance\Module->onBootstrap(Object(Zend\Mvc\MvcEvent)) #1 /var/www/html/src/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #2 /var/www/html/src/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('bootstrap', Object(Zend\Mvc\MvcEvent), Array) #3 /var/www/html/src/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(157): Zend\EventManager\EventManager->trigger('bootstrap', Object(Zend\Mvc\MvcEvent)) #4 /var/www/html/src/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(261): Zend\Mvc\Application->bootstrap(Array) #5 /var/www/html/src/public/index.php(30): Zend\Mvc\Application::init(Array) #6 {main} thrown in /var/www/html/src/module/Instance/Module.php on line 78
```
http://jaredmarkell.com/docker-and-locales/ might help to fix

**Comment by arekkas** [comment]
somewhere around here: https://github.com/serlo-org/athene2/blob/master/Dockerfile#L18-L25

**Comment by inyono** [comment]
`en_GB` was missing, so yeah, one-line copy paste @Knorrke
