### ISSUE TITLE
fatal error: /entity/unrevised

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#782]
Zusätzliche Informationen:
Normalizer\Exception\InvalidArgumentException
Datei:
/var/www/athene2/src/module/Normalizer/src/Normalizer/Normalizer.php:55
Nachricht:
Expected object but got boolean.
Stapelüberwachung:
#0 /var/www/athene2/src/module/Subject/src/Subject/Manager/SubjectManager.php(126): Normalizer\Normalizer->normalize(false)
#1 /var/www/athene2/src/module/Subject/src/Subject/Manager/SubjectManager.php(136): Subject\Manager\SubjectManager->normalize(Object(DoctrineORMModule\Proxy\__CG__\Entity\Entity\Entity), Object(Doctrine\Common\Collections\ArrayCollection))
#2 /var/www/athene2/src/module/Subject/src/Subject/Manager/SubjectManager.php(143): Subject\Manager\SubjectManager->iterEntities(Object(Doctrine\Common\Collections\ArrayCollection), Object(Doctrine\Common\Collections\ArrayCollection), 'normalize')
#3 /var/www/athene2/src/module/Subject/src/Subject/Manager/SubjectManager.php(137): Subject\Manager\SubjectManager->iterLinks(Object(Entity\Entity\Entity), Object(Doctrine\Common\Collections\ArrayCollection), 'normalize')
#4 /var/www/athene2/src/module/Subject/src/Subject/Manager/SubjectManager.php(112): Subject\Manager\SubjectManager->iterEntities(Object(Doctrine\Common\Collections\ArrayCollection), Object(Doctrine\Common\Collections\ArrayCollection), 'normalize')
#5 /var/www/athene2/src/module/Subject/src/Subject/Controller/EntityController.php(27): Subject\Manager\SubjectManager->getUnrevisedRevisions(Object(Taxonomy\Entity\TaxonomyTerm))
#6 /var/www/athene2/src/data/classes.php.cache(85): Subject\Controller\EntityController->unrevisedAction()
#7 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /var/www/athene2/src/data/classes.php.cache(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /var/www/athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/athene2/src/data/classes.php.cache(85): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/athene2/src/data/classes.php.cache(2): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#12 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /var/www/athene2/src/data/classes.php.cache(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /var/www/athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/athene2/src/data/classes.php.cache(2): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /var/www/athene2/src/public/index.php(30): Zend\Mvc\Application->run()
#17 {main}

**Comment by inyono** [comment]
Unfortunately, I can't get this to work locally since Docker is hanging somehow... I'm pretty sure the underlying issue are dead nodes, though (i.e. entities without a revision), since we normalize `$entity->getHead()`. You could reproduce this locally by creating a new article somewhere in math and exciting the editor without saving.
